Add Show instances, printCSSLength and printFontSize
JordanMartinez/purescript-halogen-svg-elems pull request #25
Opened 2021-07-27 19:01 UTC by JamieBallingall

With this PR every attribute type now has:
- An `Eq` instance
- A `Show` instance
- A `printX` function that produces what is needed by SVG

The documentation for `Show` says "While not required, it is recommended that for any expression x, the string show x be executable PureScript code which evaluates to the same value as the expression x." This is true for all types that have Show instances except `CSSLength` and `FontSize`. Fixing `CSSLength` and `FontSize` will be a (minor) breaking change.

This fixes #22 and I'll add a separate issue to track changes to `CSSLength` and `FontSize`.

2021-07-27 20:26 UTC, JordanMartinez commented
I'm not sure we need this comment below to reappear multiple times.
```
{- The documentation for Show says "While not required, it is recommended that
for any expression x, the string show x be executable PureScript code which
evaluates to the same value as the expression x." The instance of Show above
predates the use of printFontSize and does not follow that recommendation. This
may be changed in a future version and `show` when generating SVG is
depreciated. Use printFontSize instead.
-}
```
Rather, I think it should be stated more generally in the `Attributes.purs` file as a module documentation. Something like
> Each attribute has two functions: `show` from the type class `Show`
> and `printX` where `X` corresponds to the type. When printing the value
> for SVG attributes, use the `printX` function. For example
> ... example code block...
> When debugging, use either `show` or `printX`.

2021-07-27 20:29 UTC, JordanMartinez commented
Otherwise, this looks good to me!

2021-07-28 02:58 UTC, JordanMartinez commented
Can you add the module documentation comment? Then I'll merge this PR.

2021-07-28 15:04 UTC, JamieBallingall commented
Sorry about the passive-aggressive CHANGELOG commit. It suddenly occurred to me and I didn't see that you'd already commented.

I've put that Attributes level comment in but I've left smaller comments on CSSLength and FontSize to call out that they are different and are likely to change. Turns out similar comments on MarkerUnit and Orient are also required.

2021-07-28 16:01 UTC, JordanMartinez commented on src/Halogen/Svg/Attributes.purs
> +
I meant adding a doc comment [on the Attribute.purs module](https://github.com/JordanMartinez/purescript-halogen-svg-elems/blob/master/src/Halogen/Svg/Attributes.purs#L1)

For example:
```purescript
-- | Each attribute has ....
module Halogen.Svg.Attributes where
---
```

2021-07-28 19:10 UTC, JordanMartinez requested changes

2021-07-28 19:10 UTC, JordanMartinez commented on src/Halogen/Svg/Attributes.purs
> +
Could you make these `-- | ` so that they show up as documentation the module?

2021-07-29 14:04 UTC, JordanMartinez commented
Thanks!

2021-07-29 14:05 UTC, merged